package com.code.ahmad.Abstraction;

import java.util.Scanner;

public class MainApp {

	public static void main(String[] args) {
		// Creating scanner to get input from user
		Scanner scanner = new Scanner(System.in);

		// Creating instance of Employees
		Employee1 employee1= new Employee1(1,"Zubair", "malikzubair@yahoo");
		Employee3 employee2= new Employee3(2,"John", "johnDoe@yahoo");
		Employee2 employee3= new Employee2(1,"Mary", "mayKim@yahoo");

		
		System.out.println("Enter number of hours for employee1");
		employee1.setNumberOfHour(scanner.nextInt());	
		System.out.println("Enter revenue for employee1");
		employee1.setRevenue(scanner.nextInt());
		
		System.out.println("Enter number of hours for employee2");
		employee2.setNumberOfHour(scanner.nextInt());
		System.out.println("Enter revenue for employee2");
		employee2.setRevenue(scanner.nextInt());
		
		System.out.println("Enter number of hours for employee3");
		employee3.setNumberOfHour(scanner.nextInt());
		System.out.println("Enter revenue for employee3");
		employee3.setRevenue(scanner.nextInt());


		System.out.println("\nBased on revenue generated by employee1: "+employee1.getName()+". Lets see "
				+ "calculate the bonus:\n");
		employee1.calculateBonus();
		
		System.out.println("\nBased on revenue generated by employee2: "+employee2.getName()+". Lets see "
				+ "calculate the bonus:\n");
		employee2.calculateBonus();
		
		System.out.println("\nBased on revenue generated by employee3: "+employee3.getName()+". Lets see "
				+ "calculate the bonus:\n");
		employee3.calculateBonus();
	}
	

}
